version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: cmcornejocrespo/docker-get-started:0.1
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet: